const NODE_ENV = process.env.NODE_ENV
let REDISCLOUD_URL;
let REDISCLOUD_PASSWORD;
let REDISCLOUD_HOST;
let REDISCLOUD_PORT;
if (NODE_ENV === 'production') {
    REDISCLOUD_URL = process.env.REDISCLOUD_URL_LOCAL;
    REDISCLOUD_PASSWORD = process.env.REDISCLOUD_PASSWORD_LOCAL;
    REDISCLOUD_HOST = process.env.REDISCLOUD_HOST_LOCAL;
    REDISCLOUD_PORT = process.env.REDISCLOUD_PORT_LOCAL;
    
}else if (NODE_ENV === 'development') {
    REDISCLOUD_URL = process.env.REDISCLOUD_URL_CLOUD;
    REDISCLOUD_PASSWORD = process.env.REDISCLOUD_PASSWORD_CLOUD;
    REDISCLOUD_HOST = process.env.REDISCLOUD_HOST_CLOUD;
    REDISCLOUD_PORT = process.env.REDISCLOUD_PORT_CLOUD;
}


export {
    REDISCLOUD_URL,
    REDISCLOUD_PASSWORD,
    REDISCLOUD_HOST,
    REDISCLOUD_PORT
}